### ISSUE TITLE
implement: remove history entry when closing

### ISSUE THREAD

**Issue by KamelittaOida** [kakakikikeke/close-tab-right-click#1]
Can you implement this?
https://addons.mozilla.org/en-US/firefox/addon/closen-forget/

**Comment by kakakikikeke** [comment]
OK, I will also add an option to delete the history.

**Comment by kakakikikeke** [comment]
@Kamelitta I have updated to v1.1. https://addons.mozilla.org/ja/firefox/addon/close-tab-right-click/  
How is it ?

**Comment by kakakikikeke** [comment]
If you still have a question, please ask me on this issue or open other issue.
